/** Demo-only: long list to stress-test sidebar / panel scroll when option count grows. */
export const SAMPLE_OVERFLOW_MENU_ITEMS = [
  "Pin to top",
  "Mute thread",
  "Mark as read",
  "Archive",
  "Move to folder",
  "Add label",
  "Forward",
  "Export as PDF",
  "Copy link",
  "Share with team",
  "Set reminder",
  "Snooze 1 hour",
  "Snooze tomorrow",
  "Block sender",
  "Report spam",
  "Create task",
  "Add to CRM",
  "View profile",
  "Open in new tab",
  "Print",
  "Translate",
  "Summarize with AI",
  "Duplicate",
  "Merge threads",
  "Split conversation",
  "Run automation",
  "Attach file",
  "Schedule send",
] as const;
