/**
 * WhatsApp Cloud API template `language` codes — the full set Meta supports for
 * message templates. Default: `en`.
 * @see https://developers.facebook.com/docs/whatsapp/business-management-api/message-templates#supported-languages
 */
export const WHATSAPP_TEMPLATE_LANGUAGE_OPTIONS: ReadonlyArray<{
  value: string;
  label: string;
}> = [
  { value: "af", label: "Afrikaans" },
  { value: "sq", label: "Albanian" },
  { value: "ar", label: "Arabic" },
  { value: "az", label: "Azerbaijani" },
  { value: "bn", label: "Bengali" },
  { value: "bg", label: "Bulgarian" },
  { value: "ca", label: "Catalan" },
  { value: "zh_CN", label: "Chinese (China)" },
  { value: "zh_HK", label: "Chinese (Hong Kong)" },
  { value: "zh_TW", label: "Chinese (Taiwan)" },
  { value: "hr", label: "Croatian" },
  { value: "cs", label: "Czech" },
  { value: "da", label: "Danish" },
  { value: "nl", label: "Dutch" },
  { value: "en", label: "English" },
  { value: "en_GB", label: "English (UK)" },
  { value: "en_US", label: "English (US)" },
  { value: "en_AE", label: "English (UAE)" },
  { value: "en_AU", label: "English (Australia)" },
  { value: "en_CA", label: "English (Canada)" },
  { value: "en_GH", label: "English (Ghana)" },
  { value: "en_IE", label: "English (Ireland)" },
  { value: "en_IN", label: "English (India)" },
  { value: "en_JM", label: "English (Jamaica)" },
  { value: "en_MY", label: "English (Malaysia)" },
  { value: "en_NZ", label: "English (New Zealand)" },
  { value: "en_QA", label: "English (Qatar)" },
  { value: "en_SG", label: "English (Singapore)" },
  { value: "en_UG", label: "English (Uganda)" },
  { value: "en_ZA", label: "English (South Africa)" },
  { value: "et", label: "Estonian" },
  { value: "fil", label: "Filipino" },
  { value: "fi", label: "Finnish" },
  { value: "fr", label: "French" },
  { value: "fr_BE", label: "French (Belgium)" },
  { value: "fr_CA", label: "French (Canada)" },
  { value: "fr_CH", label: "French (Switzerland)" },
  { value: "fr_CI", label: "French (Côte d’Ivoire)" },
  { value: "fr_MA", label: "French (Morocco)" },
  { value: "ka", label: "Georgian" },
  { value: "de", label: "German" },
  { value: "de_AT", label: "German (Austria)" },
  { value: "de_CH", label: "German (Switzerland)" },
  { value: "el", label: "Greek" },
  { value: "gu", label: "Gujarati" },
  { value: "ha", label: "Hausa" },
  { value: "he", label: "Hebrew" },
  { value: "hi", label: "Hindi" },
  { value: "hu", label: "Hungarian" },
  { value: "id", label: "Indonesian" },
  { value: "ga", label: "Irish" },
  { value: "it", label: "Italian" },
  { value: "ja", label: "Japanese" },
  { value: "kn", label: "Kannada" },
  { value: "kk", label: "Kazakh" },
  { value: "rw_RW", label: "Kinyarwanda" },
  { value: "ko", label: "Korean" },
  { value: "ky_KG", label: "Kyrgyz (Kyrgyzstan)" },
  { value: "lo", label: "Lao" },
  { value: "lv", label: "Latvian" },
  { value: "lt", label: "Lithuanian" },
  { value: "mk", label: "Macedonian" },
  { value: "ms", label: "Malay" },
  { value: "ml", label: "Malayalam" },
  { value: "mr", label: "Marathi" },
  { value: "nb", label: "Norwegian" },
  { value: "fa", label: "Persian" },
  { value: "pl", label: "Polish" },
  { value: "pt_BR", label: "Portuguese (Brazil)" },
  { value: "pt_PT", label: "Portuguese (Portugal)" },
  { value: "pa", label: "Punjabi" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "sr", label: "Serbian" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "es", label: "Spanish" },
  { value: "es_AR", label: "Spanish (Argentina)" },
  { value: "es_CL", label: "Spanish (Chile)" },
  { value: "es_CO", label: "Spanish (Colombia)" },
  { value: "es_ES", label: "Spanish (Spain)" },
  { value: "es_MX", label: "Spanish (Mexico)" },
  { value: "es_PE", label: "Spanish (Peru)" },
  { value: "sw", label: "Swahili" },
  { value: "sv", label: "Swedish" },
  { value: "ta", label: "Tamil" },
  { value: "te", label: "Telugu" },
  { value: "th", label: "Thai" },
  { value: "tr", label: "Turkish" },
  { value: "uk", label: "Ukrainian" },
  { value: "ur", label: "Urdu" },
  { value: "uz", label: "Uzbek" },
  { value: "vi", label: "Vietnamese" },
  { value: "zu", label: "Zulu" },
];

export const DEFAULT_WHATSAPP_TEMPLATE_LANGUAGE = "en";
